#!/usr/bin/env python3
# This is the dictionary, a built-in type in python, 
# to describe figure's parameters to be generated by PKUNCEPVIEWER
# by X. Wen, Peking Univ, Apr 2018

'''
Notes
ID :        302001
            30      - Type: 30=Lat-Time contours
              20    - Month: 20 = 12-month, one by one
                01  - figure number
LonRange :  [0,360]     - Zonal mean
            [0,180]     - Eastern Hemisphere zonal mean
            [100,120]   - Eastern China zonal mean
'''

FIG = [

#########################
# Section 1. Zonal Mean #
#########################
# Copy and paste below 18 lines
{  'ID'           : 302001                               ,  # Basic
   'TYPE'         : 'lat-time'                           ,
   'Description'  : 'Zonal Mean U Wind at 200mb'         ,
   'DescriptionC' : '纬向平均的U200'                     ,
   'FigTitle'     : 'Zonal Mean U Wind\n200mb'           ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'PresLev'      : 200                                  ,
   'LonRange'     : [0,360]                              ,
   'Levels'       : 'np.arange(-15,46,2.5)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 8                                    ,
   'FileOut'      : 'ncep1_anncycle_u200.pdf'            }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 302002                               ,  # Basic
   'TYPE'         : 'lat-time'                           ,
   'Description'  : 'Zonal Mean Z500'                    ,
   'DescriptionC' : '纬向平均的Z500'                     ,
   'FigTitle'     : 'Zonal Mean Geopotential Height\n500mb' ,  # Key info
   'FileIn'       : ['ncep1/hgt.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].hgt'                           ,
   'PresLev'      : 500                                  ,
   'LonRange'     : [0,360]                              ,
   'Levels'       : 'np.arange(4800,5925,25)'            ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 8                                    ,
   'FileOut'      : 'ncep1_anncycle_z500.pdf'            }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 302003                               ,  # Basic
   'TYPE'         : 'lat-time'                           ,
   'Description'  : 'Zonal Mean T2'                      ,
   'DescriptionC' : '纬向平均的T2'                       ,
   'FigTitle'     : 'Zonal Mean Surface Air Temperature\n2m' ,  # Key info
   'FileIn'       : ['ncep1/air.2m.mon.ltm.nc',]         ,
   'Compute'      : 'f[0].air-273.15'                    ,
   'PresLev'      : 0                                    ,
   'LonRange'     : [0,360]                              ,
   'Levels'       : 'np.arange(-60,31,2)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 8                                    ,
   'FileOut'      : 'ncep1_anncycle_t2.pdf'              }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 302004                               ,  # Basic
   'TYPE'         : 'lat-time'                           ,
   'Description'  : 'East Asian SLP'                     ,
   'DescriptionC' : '东亚地区的SLP'                      ,
   'FigTitle'     : 'East Asian Sea Level Pressure\n100E-140E'    ,  # Key info
   'FileIn'       : ['ncep1/slp.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].slp'                           ,
   'PresLev'      : 0                                    ,
   'LonRange'     : [100,140]                            ,
   'Levels'       : 'np.arange(970,1061,2)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 8                                    ,
   'FileOut'      : 'ncep1_anncycle_slp.pdf'             }  # Output
,#########################################################


]
