#!/usr/bin/env python3
# This is the dictionary, a built-in type in python, 
# to describe figure's parameters to be generated by PKUNCEPVIEWER
# by X. Wen, Peking Univ, Apr 2018

'''
Notes
ID :        200101
            21      - Type: 21=Lon-Pressure contours
              01    - Month: 1-12, 20=ANN, 21=DJF, 22=MAM, 23=JJA, 24=SON
                01  - figure number
Month :     Single month  : 1,2,...,11,12 = Jan,Feb,...,Nov,Dec
            Seasonal mean : 'DJF','MAM','JJA','SON'
            Annual mean   : 'ANN'
LatRange :  [-5,5]   - Equatorial mean
            [0,90]   - Northern Hemisphere mean
            [-90,90] - Southern Hemisphere mean
'''

FIG = [

######################
# Section 1. January #
######################
# Copy and paste below 19 lines
{  'ID'           : 210101                               ,  # Basic
   'TYPE'         : 'lon-pres'                           ,
   'Description'  : 'Jan V Wind (Cross-section along Equator)' ,
   'DescriptionC' : '1月赤道附近的越赤道V风'             ,
   'FigTitle'     : 'V Wind along Equator Cross-section\nJan'  ,  # Key info
   'FileIn'       : ['ncep1/vwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].vwnd'                          ,
   'LatRange'     : [-5,5]                               ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(-12,12.5,0.5)'            ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_jan_v.pdf'                    }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 210102                               ,  # Basic
   'TYPE'         : 'lon-pres'                           ,
   'Description'  : 'Jan U Wind (Cross-section along Equator)' ,
   'DescriptionC' : '1月赤道附近的U风'                   ,
   'FigTitle'     : 'U Wind along Equator Cross-section\nJan'  ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'LatRange'     : [-5,5]                               ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(-25,25.5,1)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_jan_u.pdf'                    }  # Output
,#########################################################


######################
# Section 2. July    #
######################
# Copy and paste below 19 lines
{  'ID'           : 210701                               ,  # Basic
   'TYPE'         : 'lon-pres'                           ,
   'Description'  : 'Jul V Wind (Cross-section along Equator)' ,
   'DescriptionC' : '7月赤道附近的越赤道V风'             ,
   'FigTitle'     : 'V Wind along Equator Cross-section\nJul'  ,  # Key info
   'FileIn'       : ['ncep1/vwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].vwnd'                          ,
   'LatRange'     : [-5,5]                               ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 7                                    ,
   'Levels'       : 'np.arange(-12,12.5,0.5)'            ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_jul_v.pdf'                    }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 210702                               ,  # Basic
   'TYPE'         : 'lon-pres'                           ,
   'Description'  : 'Jul U Wind (Cross-section along Equator)' ,
   'DescriptionC' : '7月赤道附近的U风'                   ,
   'FigTitle'     : 'U Wind along Equator Cross-section\nJul'  ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'LatRange'     : [-5,5]                               ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 7                                    ,
   'Levels'       : 'np.arange(-25,25.5,1)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_jul_u.pdf'                    }  # Output
,#########################################################


######################
# Section 3. ANN     #
######################
# Copy and paste below 19 lines
{  'ID'           : 212001                               ,  # Basic
   'TYPE'         : 'lon-pres'                           ,
   'Description'  : 'ANN V Wind (Cross-section along Equator)' ,
   'DescriptionC' : '年平均赤道附近的越赤道V风'             ,
   'FigTitle'     : 'V Wind along Equator Cross-section\nANN'  ,  # Key info
   'FileIn'       : ['ncep1/vwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].vwnd'                          ,
   'LatRange'     : [-5,5]                               ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 'ANN'                                ,
   'Levels'       : 'np.arange(-12,12.5,0.5)'            ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_ann_v.pdf'                    }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 212002                               ,  # Basic
   'TYPE'         : 'lon-pres'                           ,
   'Description'  : 'ANN U Wind (Cross-section along Equator)' ,
   'DescriptionC' : '年平均赤道附近的U风'                ,
   'FigTitle'     : 'U Wind along Equator Cross-section\nANN'  ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'LatRange'     : [-5,5]                               ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 'ANN'                                ,
   'Levels'       : 'np.arange(-15,15.5,0.5)'            ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_ann_u.pdf'                    }  # Output
,#########################################################

]
