#!/usr/bin/env python3
# This is the dictionary, a built-in type in python, 
# to describe figure's parameters to be generated by PKUNCEPVIEWER
# by X. Wen, Peking Univ, Apr 2018

#import numpy as np

FIG = [

# Copy and paste below 19 lines
{  'ID'           : 100001                               ,  # Basic
   'TYPE'         : 'pres-lat-lon'                       ,
   'Description'  : 'Jan Geopotential Height at 500mb'   ,
   'DescriptionC' : '1月500mb高度场'                     ,
   'FigTitle'     : 'Geopotential Height at 500mb\nJan'  ,  # Key info
   'FileIn'       : ['ncep1/hgt.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].hgt'                           ,
   'PresLev'      : 500                                  ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(4950,5950,50)'            ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'Domain'       : [-90,90,0,360]                       ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_z500.pdf'                 }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 100002                               ,  # Basic
   'TYPE'         : 'pres-lat-lon'                       ,
   'Description'  : 'Jan U Wind at 200mb'                ,
   'DescriptionC' : '1月200mb纬向风'                     ,
   'FigTitle'     : 'U Wind at 200mb\nJan'               ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'PresLev'      : 200                                  ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(-60,61,5)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'Domain'       : [-90,90,0,360]                       ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_u200.pdf'                 }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 100003                               ,  # Basic
   'TYPE'         : 'lat-lon'                            ,
   'Description'  : 'Jan Sea Level Pressure'             ,
   'DescriptionC' : '1月海平面气压场'                    ,
   'FigTitle'     : 'Sea Level Pressure\nJan'            ,  # Key info
   'FileIn'       : ['ncep1/slp.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].slp'                           ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(984,1041,2)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'hPa'                                ,
   'Domain'       : [-90,90,0,360]                       ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_slp.pdf'                  }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 100004                               ,  # Basic
   'TYPE'         : 'lat-lon'                            ,
   'Description'  : 'Jan Surface Air Temperature at 2m'  ,
   'DescriptionC' : '1月地表气温(2米)'                   ,
   'FigTitle'     : 'Surface Air Temperature at 2m\nJan' ,  # Key info
   'FileIn'       : ['ncep1/air.2m.mon.ltm.nc',]         ,
   'Compute'      : 'f[0].air-273.15'                    ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(-40,40,4)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'Celsius'                            ,
   'Domain'       : [-90,90,0,360]                       ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_t2.pdf'                   }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 100005                               ,  # Basic
   'TYPE'         : 'lat-lon'                            ,
   'Description'  : 'Jan Precipitation'                  ,
   'DescriptionC' : '1月降水'                            ,
   'FigTitle'     : 'Precipitation\nJan'                 ,  # Key info
   'FileIn'       : ['ncep1/prate.sfc.mon.ltm.nc',]      ,
   'Compute'      : 'f[0].prate*24*60*60'                ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(0,13,1)'                  ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'mm/day'                             ,
   'Domain'       : [-90,90,0,360]                       ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_precip.pdf'               }  # Output
,#########################################################

# Copy and paste below 20 lines
{  'ID'           : 100006                               ,  # Basic
   'TYPE'         : 'pres-lat-lon-vec'                   ,
   'Description'  : 'Jan Wind at 850mb'                  ,
   'DescriptionC' : '1月850mb风场'                       ,
   'FigTitle'     : 'Wind at 850mb\nJan'                 ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',
                     'ncep1/vwnd.mon.ltm.nc']            ,
   'Compute'      : 'f[0].uwnd, f[1].vwnd'               ,
   'PresLev'      : 850                                  ,
   'Month'        : 1                                    ,
   'VecLen'       : 10                                   ,  # Plotting arguments
   'Unit'         : 'm/s'                                ,
   'Density'      : 2                                    ,
   'Domain'       : [-90,90,0,360]                       ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_wind850.pdf'              }  # Output
,#########################################################

]

