#!/usr/bin/env python3
# This is the dictionary, a built-in type in python, 
# to describe figure's parameters to be generated by PKUNCEPVIEWER
# by X. Wen, Peking Univ, Apr 2018

'''
Notes
ID :        200101
            20      - Type: 20=Lat-Pressure contours
              01    - Month: 1-12, 20=ANN, 21=DJF, 22=MAM, 23=JJA, 24=SON
                01  - figure number
Month :     Single month  : 1,2,...,11,12 = Jan,Feb,...,Nov,Dec
            Seasonal mean : 'DJF','MAM','JJA','SON'
            Annual mean   : 'ANN'
LonRange :  [0,360]     - Zonal mean
            [0,180]     - Eastern Hemisphere zonal mean
            [100,120]   - Eastern China zonal mean
'''

FIG = [

######################
# Section 1. January #
######################
# Copy and paste below 19 lines
{  'ID'           : 200101                               ,  # Basic
   'TYPE'         : 'lat-pres'                           ,
   'Description'  : 'Jan U Wind (Zonal Mean)'            ,
   'DescriptionC' : '1月纬向平均的U风'                   ,
   'FigTitle'     : 'Zonal Mean U Wind\nJan'             ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'LonRange'     : [0,360]                              ,
   'LevRange'     : [1000,100]                            ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(-20,46,2.5)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_jan_u.pdf'                    }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 200102                               ,  # Basic
   'TYPE'         : 'lat-pres'                           ,
   'Description'  : 'Jan Temperature (Zonal Mean)'       ,
   'DescriptionC' : '1月纬向平均温度'                    ,
   'FigTitle'     : 'Zonal Mean Temperature\nJan'        ,  # Key info
   'FileIn'       : ['ncep1/air.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].air'                           ,
   'LonRange'     : [0,360]                              ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(-80,33,4)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'deg_C'                              ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_jan_temperature.pdf'          }  # Output
,#########################################################


######################
# Section 2. July    #
######################
# Copy and paste below 19 lines
{  'ID'           : 200701                               ,  # Basic
   'TYPE'         : 'lat-pres'                           ,
   'Description'  : 'Jul U Wind (Zonal Mean)'            ,
   'DescriptionC' : '7月纬向平均的U风'                   ,
   'FigTitle'     : 'Zonal Mean U Wind\nJul'             ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'LonRange'     : [0,360]                              ,
   'LevRange'     : [1000,100]                            ,
   'Month'        : 7                                    ,
   'Levels'       : 'np.arange(-20,46,2.5)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_jul_u.pdf'                    }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 200702                               ,  # Basic
   'TYPE'         : 'lat-pres'                           ,
   'Description'  : 'Jul Temperature (Zonal Mean)'       ,
   'DescriptionC' : '7月纬向平均温度'                    ,
   'FigTitle'     : 'Zonal Mean Temperature\nJul'        ,  # Key info
   'FileIn'       : ['ncep1/air.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].air'                           ,
   'LonRange'     : [0,360]                              ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 7                                    ,
   'Levels'       : 'np.arange(-80,33,4)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'deg_C'                              ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_jul_temperature.pdf'          }  # Output
,#########################################################


######################
# Section 3. ANN     #
######################
# Copy and paste below 19 lines
{  'ID'           : 202001                               ,  # Basic
   'TYPE'         : 'lat-pres'                           ,
   'Description'  : 'ANN U Wind (Zonal Mean)'            ,
   'DescriptionC' : '年平均纬向平均的U风'                ,
   'FigTitle'     : 'Zonal Mean U Wind\nANN'             ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'LonRange'     : [0,360]                              ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 'ANN'                                ,
   'Levels'       : 'np.arange(-8,33,2)'                 ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'm/s'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_ann_u.pdf'                    }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 202002                               ,  # Basic
   'TYPE'         : 'lat-pres'                           ,
   'Description'  : 'ANN Temperature (Zonal Mean)'       ,
   'DescriptionC' : '年平均纬向平均温度'                 ,
   'FigTitle'     : 'Zonal Mean Temperature\nANN'        ,  # Key info
   'FileIn'       : ['ncep1/air.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].air'                           ,
   'LonRange'     : [0,360]                              ,
   'LevRange'     : [1000,100]                           ,
   'Month'        : 'ANN'                                ,
   'Levels'       : 'np.arange(-80,33,4)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'deg_C'                              ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_ann_temperature.pdf'          }  # Output
,#########################################################

]
