#!/usr/bin/env python3
# This is the dictionary, a built-in type in python, 
# to describe figure's parameters to be generated by PKUNCEPVIEWER
# by X. Wen, Peking Univ, Apr 2018

'''
Notes
ID : 100101
     11      - Cat: 11=NP maps
       01    - Month: 1-12, 20=ANN, 21=DJF, 22=MAM, 23=JJA, 24=SON
         01  - figure number
Month : Single month  : 1,2,...,11,12 = Jan,Feb,...,Nov,Dec
        Seasonal mean : 'DJF','MAM','JJA','SON'
        Annual mean   : 'ANN'
Domain : [SouthmostLat,NorthmostLat,6-Clock-Lon/CentralLon]
'''

FIG = [

######################
# Section 1. January #
######################
# Copy and paste below 19 lines
{  'ID'           : 110101                               ,  # Basic
   'TYPE'         : 'pres-np'                            ,
   'Description'  : 'Jan Geopotential Height at 500mb'   ,
   'DescriptionC' : '1月500mb高度场'                     ,
   'FigTitle'     : 'Geopotential Height at 500mb\nJan'  ,  # Key info
   'FileIn'       : ['ncep1/hgt.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].hgt'                           ,
   'PresLev'      : 500                                  ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(4950,5950,50)'            ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_z500.pdf'                 }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 110102                               ,  # Basic
   'TYPE'         : 'pres-np'                            ,
   'Description'  : 'Jan U Wind at 200mb'                ,
   'DescriptionC' : '1月200mb纬向风'                     ,
   'FigTitle'     : 'U Wind at 200mb\nJan'               ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'PresLev'      : 200                                  ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(-4,81,4)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_u200.pdf'                 }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 110103                               ,  # Basic
   'TYPE'         : 'np'                                 ,
   'Description'  : 'Jan Sea Level Pressure'             ,
   'DescriptionC' : '1月海平面气压场'                    ,
   'FigTitle'     : 'Sea Level Pressure\nJan'            ,  # Key info
   'FileIn'       : ['ncep1/slp.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].slp'                           ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(984,1041,2)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'hPa'                                ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_slp.pdf'                  }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 110104                               ,  # Basic
   'TYPE'         : 'np'                                 ,
   'Description'  : 'Jan Surface Air Temperature at 2m'  ,
   'DescriptionC' : '1月地表气温(2米)'                   ,
   'FigTitle'     : 'Surface Air Temperature at 2m\nJan' ,  # Key info
   'FileIn'       : ['ncep1/air.2m.mon.ltm.nc',]         ,
   'Compute'      : 'f[0].air-273.15'                    ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(-40,40,4)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'Celsius'                            ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_t2.pdf'                   }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 110105                               ,  # Basic
   'TYPE'         : 'np'                                 ,
   'Description'  : 'Jan Precipitation'                  ,
   'DescriptionC' : '1月降水'                            ,
   'FigTitle'     : 'Precipitation\nJan'                 ,  # Key info
   'FileIn'       : ['ncep1/prate.sfc.mon.ltm.nc',]      ,
   'Compute'      : 'f[0].prate*24*60*60'                ,
   'Month'        : 1                                    ,
   'Levels'       : 'np.arange(0,13,1)'                  ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'mm/day'                             ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_precip.pdf'               }  # Output
,#########################################################

# Copy and paste below 20 lines
{  'ID'           : 110106                               ,  # Basic
   'TYPE'         : 'pres-np-vec'                        ,
   'Description'  : 'Jan Wind at 850mb (BIG ISSUE HERE)' ,
   'DescriptionC' : '1月850mb风场'                       ,
   'FigTitle'     : 'Wind at 850mb\nJan'                 ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',
                     'ncep1/vwnd.mon.ltm.nc']            ,
   'Compute'      : 'f[0].uwnd, f[1].vwnd'               ,
   'PresLev'      : 850                                  ,
   'Month'        : 1                                    ,
   'VecLen'       : 10                                   ,  # Plotting arguments
   'Unit'         : 'm/s'                                ,
   'Density'      : 2                                    ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jan_wind850.pdf'              }  # Output
,#########################################################

######################
# Section 2. July    #
######################
# Copy and paste below 19 lines
{  'ID'           : 110701                               ,  # Basic
   'TYPE'         : 'pres-np'                            ,
   'Description'  : 'Jul Geopotential Height at 500mb'   ,
   'DescriptionC' : '7月500mb高度场'                     ,
   'FigTitle'     : 'Geopotential Height at 500mb\nJul'  ,  # Key info
   'FileIn'       : ['ncep1/hgt.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].hgt'                           ,
   'PresLev'      : 500                                  ,
   'Month'        : 7                                    ,
   'Levels'       : 'np.arange(4800,6000,50)'            ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jul_z500.pdf'                 }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 110702                               ,  # Basic
   'TYPE'         : 'pres-np'                            ,
   'Description'  : 'Jul U Wind at 200mb'                ,
   'DescriptionC' : '7月200mb纬向风'                     ,
   'FigTitle'     : 'U Wind at 200mb\nJul'               ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'PresLev'      : 200                                  ,
   'Month'        : 7                                    ,
   'Levels'       : 'np.arange(-35,36,2)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jul_u200.pdf'                 }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 110703                               ,  # Basic
   'TYPE'         : 'np'                                 ,
   'Description'  : 'Jul Sea Level Pressure'             ,
   'DescriptionC' : '7月海平面气压场'                    ,
   'FigTitle'     : 'Sea Level Pressure\nJul'            ,  # Key info
   'FileIn'       : ['ncep1/slp.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].slp'                           ,
   'Month'        : 7                                    ,
   'Levels'       : 'np.arange(980,1035,2)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'hPa'                                ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jul_slp.pdf'                  }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 110704                               ,  # Basic
   'TYPE'         : 'np'                                 ,
   'Description'  : 'Jul Surface Air Temperature at 2m'  ,
   'DescriptionC' : '7月地表气温(2米)'                   ,
   'FigTitle'     : 'Surface Air Temperature at 2m\nJul' ,  # Key info
   'FileIn'       : ['ncep1/air.2m.mon.ltm.nc',]         ,
   'Compute'      : 'f[0].air-273.15'                    ,
   'Month'        : 7                                    ,
   'Levels'       : 'np.arange(-10,41,2)'                  ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'Celsius'                            ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jul_t2.pdf'                   }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 110705                               ,  # Basic
   'TYPE'         : 'np'                                 ,
   'Description'  : 'Jul Precipitation'                  ,
   'DescriptionC' : '7月降水'                            ,
   'FigTitle'     : 'Precipitation\nJul'                 ,  # Key info
   'FileIn'       : ['ncep1/prate.sfc.mon.ltm.nc',]      ,
   'Compute'      : 'f[0].prate*24*60*60'                ,
   'Month'        : 7                                    ,
   'Levels'       : 'np.arange(0,13,1)'                  ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'mm/day'                             ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jul_precip.pdf'               }  # Output
,#########################################################

# Copy and paste below 20 lines
{  'ID'           : 110706                               ,  # Basic
   'TYPE'         : 'pres-np-vec'                        ,
   'Description'  : 'Jul Wind at 850mb (BIG ISSUE HERE)' ,
   'DescriptionC' : '7月850mb风场'                       ,
   'FigTitle'     : 'Wind at 850mb\nJul'                 ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',
                     'ncep1/vwnd.mon.ltm.nc']            ,
   'Compute'      : 'f[0].uwnd, f[1].vwnd'               ,
   'PresLev'      : 850                                  ,
   'Month'        : 7                                    ,
   'VecLen'       : 10                                   ,  # Plotting arguments
   'Unit'         : 'm/s'                                ,
   'Density'      : 2                                    ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_jul_wind850.pdf'              }  # Output
,#########################################################


######################
# Section 3. ANN     #
######################
# Copy and paste below 19 lines
{  'ID'           : 112001                               ,  # Basic
   'TYPE'         : 'pres-np'                            ,
   'Description'  : 'ANN Geopotential Height at 500mb'   ,
   'DescriptionC' : '年平均500mb高度场'                  ,
   'FigTitle'     : 'Geopotential Height at 500mb\nANN'  ,  # Key info
   'FileIn'       : ['ncep1/hgt.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].hgt'                           ,
   'PresLev'      : 500                                  ,
   'Month'        : 'ANN'                                ,
   'Levels'       : 'np.arange(4900,5950,50)'            ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_ann_z500.pdf'                 }  # Output
,#########################################################

# Copy and paste below 19 lines
{  'ID'           : 112002                               ,  # Basic
   'TYPE'         : 'pres-np'                            ,
   'Description'  : 'ANN U Wind at 200mb'                ,
   'DescriptionC' : '年平均200mb纬向风'                  ,
   'FigTitle'     : 'U Wind at 200mb\nANN'               ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'PresLev'      : 200                                  ,
   'Month'        : 'ANN'                                ,
   'Levels'       : 'np.arange(-45,46,5)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_ann_u200.pdf'                 }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 112003                               ,  # Basic
   'TYPE'         : 'np'                                 ,
   'Description'  : 'ANN Sea Level Pressure'             ,
   'DescriptionC' : '年平均海平面气压场'                 ,
   'FigTitle'     : 'Sea Level Pressure\nANN'            ,  # Key info
   'FileIn'       : ['ncep1/slp.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].slp'                           ,
   'Month'        : 'ANN'                                ,
   'Levels'       : 'np.arange(1000,1026,1)'              ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'hPa'                                ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_ann_slp.pdf'                  }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 112004                               ,  # Basic
   'TYPE'         : 'np'                                 ,
   'Description'  : 'ANN Surface Air Temperature at 2m'  ,
   'DescriptionC' : '年平均地表气温(2米)'                ,
   'FigTitle'     : 'Surface Air Temperature at 2m\nANN' ,  # Key info
   'FileIn'       : ['ncep1/air.2m.mon.ltm.nc',]         ,
   'Compute'      : 'f[0].air-273.15'                    ,
   'Month'        : 'ANN'                                ,
   'Levels'       : 'np.arange(-30,31,2)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'Celsius'                            ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_ann_t2.pdf'                   }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 112005                               ,  # Basic
   'TYPE'         : 'np'                                 ,
   'Description'  : 'ANN Precipitation'                  ,
   'DescriptionC' : '年平均降水'                         ,
   'FigTitle'     : 'Precipitation\nANN'                 ,  # Key info
   'FileIn'       : ['ncep1/prate.sfc.mon.ltm.nc',]      ,
   'Compute'      : 'f[0].prate*24*60*60'                ,
   'Month'        : 'ANN'                                ,
   'Levels'       : 'np.arange(0,11,0.5)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'mm/day'                             ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_ann_precip.pdf'               }  # Output
,#########################################################

# Copy and paste below 20 lines
{  'ID'           : 112006                               ,  # Basic
   'TYPE'         : 'pres-np-vec'                        ,
   'Description'  : 'ANN Wind at 850mb (BIG ISSUE HERE)' ,
   'DescriptionC' : '年平均850mb风场'                    ,
   'FigTitle'     : 'Wind at 850mb\nANN'                 ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',
                     'ncep1/vwnd.mon.ltm.nc']            ,
   'Compute'      : 'f[0].uwnd, f[1].vwnd'               ,
   'PresLev'      : 850                                  ,
   'Month'        : 'ANN'                                ,
   'VecLen'       : 10                                   ,  # Plotting arguments
   'Unit'         : 'm/s'                                ,
   'Density'      : 2                                    ,
   'Domain'       : [15,90,90]                           ,
   'MapRes'       : 'c'                                  ,
   'CountryLine'  : False                                ,
   'FileOut'      : 'ncep1_ann_wind850.pdf'              }  # Output
,#########################################################


]

