#!/usr/bin/env python3
# This is the dictionary, a built-in type in python, 
# to describe figure's parameters to be generated by PKUNCEPVIEWER
# by X. Wen, Peking Univ, Apr 2018

'''
Notes
ID :        312001
            31      - Type: 31 = Lon-Time
              20    - Month: 20 = 12-month, one by one
                01  - figure number
LatRange :  [-5,5]   - Equatorial mean
            [0,90]   - Northern Hemisphere mean
            [-90,90] - Southern Hemisphere mean
'''

FIG = [

######################
# Section 1.         #
######################
# Copy and paste below 18 lines
{  'ID'           : 312001                               ,  # Basic
   'TYPE'         : 'lon-time'                           ,
   'Description'  : 'Z500 along 25N'                     ,
   'DescriptionC' : '北纬25度的Z500高度场'               ,
   'FigTitle'     : 'Z500 Hovmueller Diagram\n25N'       ,  # Key info
   'FileIn'       : ['ncep1/hgt.mon.ltm.nc',]            ,
   'Compute'      : 'f[0].hgt'                           ,
   'LatRange'     : [22,28]                              ,
   'PresLev'      : 500                                  ,
   'Levels'       : 'np.arange(5740,5941,5)'             ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_anncycle_z500_25N.pdf'        }  # Output
,#########################################################

# Copy and paste below 18 lines
{  'ID'           : 312002                               ,  # Basic
   'TYPE'         : 'lon-time'                           ,
   'Description'  : 'U200 along 20N'                     ,
   'DescriptionC' : '北纬20度的U200风场'                 ,
   'FigTitle'     : 'U200 Hovmueller Diagram\n20N'       ,  # Key info
   'FileIn'       : ['ncep1/uwnd.mon.ltm.nc',]           ,
   'Compute'      : 'f[0].uwnd'                          ,
   'LatRange'     : [17,23]                              ,
   'PresLev'      : 200                                  ,
   'Levels'       : 'np.arange(-40,41,1)'                ,  # Plotting arguments
   'ColorMap'     : 'jet'                                ,
   'Unit'         : 'gpm'                                ,
   'AddContour'   : True                                 ,
   'NumContours'  : 10                                   ,
   'FileOut'      : 'ncep1_anncycle_u200_20N.pdf'        }  # Output
,#########################################################


]
